sudo: required

language: node_js
node_js:
  - node

cache:
  - node_modules

services:
  - docker

env:
  global:
  # HEROKU_API_KEY
  - secure: beOVVru7HiJET/1WClIYsxZiCSgoovKekH/LG5gF0Fd0+Gg1IBE9HcFn2mypFnZelBdfOzjU2x842wZxtDcsYmGY/R0FwSXnoQjSgFzIKBjxTVK8RwMA7tT+/zcUqrDxrG9LmzleZ9mPbhaUsMdHatiNAx7T9x9bw8lj3ubLbzwj9HoQrjIJSnLZNNzaBd90viYYC7cdE8IaXddsE6SLI/CBwF4r1OZkLyQNwyANaAmEQP/Iuwscp6GeOKlrm2XudrDkQ8Pp6Ypnhud80qVZBoTAemujT+k9o2QEtCWwlAR5UEjrP/51fGQxQg32eU+ppBj2/9LuvMIfoJ7w9sF/Ilz2plhg745UZDLxzuFfdsY/IbvpQ+kxtD8RsyvMRLIdx0tZ2EiOw7OsMdNwhE5Zmn95SE337FeGwKjwv0HzGX/XhPrE7KFyPxv2HU6V4M0alektYzqi3O7HUPoLx9O5Ig8K4/mkelYailEA0PHq9r8ZhrMN1Omj0XOBOpBmGsr7tL5vghEmzurnBUr8ZUjw2whRCOVIR6LIEaoIsdVik/a58wFcOyZ6xWivgLClgMclHZvAxi3zj8PRuHyIakwuezCLGCJ+2NVsW8pDg63WuKsOK+db0gJjC78mdYz4tZnzeLv3hsnB8mDRl8fMi/IwFsKjYk3SLGf6ylTFxldupnM=
  # DOCKER_USERNAME
  -secure: gcP0JW0KaP8BjgaJxeT4jqk8T8ATjjgIbI20F4/jDbOMb9Y76SLIASUqSNVLAP/u9m1YKtbRhhQsSGlYunRhr30T+fUNk3cvkVvtRxww2fEwNstv8nZEfYF5LHhX560YQ9jnZBhqogYxJe2ctfLDZnbr53L/tb+MPi5B43UEN1/4chctPSM3GpXMoD9IxoY5FotkyaJP3EhnwGvy85eBnDAZ0HHrp6MF+MLgW37xgFTsU+oHpFjIgMc3B0K0rkq4xbvRUHEIoPjQmAJDviz10nzNvptYNaxIdvncE59BG6KPLXvskhmaClc/K7aoCQFfYkwazVajhpKUx57dyZtgT6O201eT7R7ssc0OxeCgP8VcyOWUCA6zlNX0PJ47L15KM2Vb5WIU0o2PdLZa9VZNmAJsjn4IwLJM8mbHm9mhXg2X2njn77Daiqjq+K9/2w/XYbH9FPNFLNJ31ycItN2PeSAfGQlBScc2A6YWf5rOJaAm0DZplqhfOHUgFvtSjwYki3WffEnpyndxEH4FY3O36rOVQ/fqVTFJKU+2mnveVM2CLy9NYXBhq2Q3ryniv9HMtDDYpEYHehdUSkBQJzFjK1nBGEFTOxyegc2dkAEv+UQbqOD8mdxvVu3rF02HpxXyesHR1kBuxVao2yfmxQVp7Q5CwhJrc2QgQhHA5GUhyms=


before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

script:
  - yarn run flow
  - yarn run lint

# When we have succeeded, then release to staging. Then, when QA'ed,
# the staging app will be promoted to production.
after_success:
  - .travis/after-success.sh

branches:
  only:
  - master

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
  slack:
    secure: olaEfS4ESRZlQK3Ead/m2HKio+TE3UPeX9uQX54qsaKcKDbP9jYhO8OaDOfEvh4Zgp/VSyN1ak0sRzaWih5gu0qEtnEXu1Hq0dsWEOxKOgp7dmVnhXCsZDC44MPySnodfmg5+rhNurnRxhHyECVjxR4d22oumcEagz7FKigC7xiU0OLLy1kaRR44VRN0RpaEgwJRrlSPa7kndZrUNHNrGL7hJcPb4HVFomR136muHQRXlQw7BSH3UT7vyS28eTWKsA1tLSFKIqDGKRmUdQi606zL48Y/fhyUxavOoAHIf/yQO7H7jSPgLgrOBsmrNuk0mNaK85WM3PglO/MW8+seyHFQTnPgD9//ASRVJiwKF5R2nqil4XCNmec1jbya+odIZacmXehKELGjm/y4l2Fs/ATfrTAtZ8gkq+8GtrzTMMUBZYSBTAj6WmjyohgnVbEjtWG7FhUrl+c2PXOiZsugNmkgbYfCBiQQK8CxbKTSyqd5KMwaVJepVQm2zTCT/BigReaznMNYVbrqDG+Hi0zshIbMpIifhukw8VwL4cQwWvC7WVg+I7cJnThQATL00MJezxndsNVrtaTXXseFcaixR6IKmqcTbkkCpA96gkQX0Hsv95xh+K5iqR/lXRmC3opV0+IKmHGGYrwJ5v+ppYrDSensPI7c6U7eGZVLL9gHSr0=
